language: php

env:
  global:
    - COMPOSER_MEMORY_LIMIT=-1
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
install:
  - composer install --no-interaction
script:
  - composer test
after_success:
 - travis_retry php vendor/bin/php-coveralls -v
