name: Test
on:
  - push
  - pull_request

jobs:
  test:
    name: Run tests
    runs-on: 'ubuntu-20.04'
    strategy:
      fail-fast: false
      matrix:
        composer:
          - 1
          - 2
        php-versions:
          - "7.0"
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
    steps:
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Select the composer version
        run: |
          composer --version
          composer self-update
          composer self-update --${{ matrix.composer }}
          composer --version

      - name: Dump composer verson
        run: composer --version

      - name: Validate composer.json
        run: composer --verbose validate

      - name: Install dependencies
        if: matrix.php-versions != 7.0
        run: composer --verbose install
    
      - name: Install dependencies
        if: matrix.php-versions == 7.0
        run: composer --verbose --ignore-platform-reqs install

      - name: Install patches and phpstan if we have to
        if: matrix.php-versions != 7.0
        run: composer require --dev cweagans/composer-patches phpstan/phpstan

      - name: Remove and reinstall phpunit
        if: matrix.php-versions != 7.0
        run: |
          rm -rf vendor/phpunit
          composer install

      # Since this is a library we do not have a lock file. But at this point we do, and now we want to use that for the
      # tests we are about to run.
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}-${{ matrix.php-version }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php-version }}

      - name: Run tests
        run: composer test
        env:
          COMPOSER_VERSION: ${{ matrix.composer }}

      - name: run phpstan
        if: matrix.php-versions != 7.0
        run: phpstan analyze src tests


     L

