name: Test
on:
  - push
  - pull_request

jobs:
  test:
    name: Run tests
    runs-on: 'ubuntu-20.04'
    strategy:
      fail-fast: false
      matrix:
        composer:
          - 2
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
    steps:
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Select the composer version
        run: |
          composer --version
          composer self-update
          composer self-update --${{ matrix.composer }}
          composer --version

      - name: Dump composer verson
        run: composer --version

      - name: Validate composer.json
        run: composer --verbose validate

      - name: Install dependencies
        run: composer --verbose install

      - name: Run tests
        run: composer test
        env:
          COMPOSER_VERSION: ${{ matrix.composer }}

      - name: Coveralls
        if: matrix.php-version == 7.4
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
        run: |
          php vendor/bin/php-coveralls -v


  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Close parallel build
        uses: coverallsapp/github-action@v1
        with:
          parallel-finished: true
